### ISSUE TITLE
Implement C4View

### ISSUE THREAD

**Issue by aleph7** [C4Framework/C4iOS#184]
After talking to @C4Code, we decided to go with a wrapper around `UIView` as opposed to an extension to `UIView`. The main reason is to have more control over property types, for instance we want `frame` to be a `C4Rect` not a `CGRect`. This is how `C4View` will look like:

    public class C4View : MediaObject, Visible {
        var view: UIView
        public var frame: C4Rect;
    }

**Comment by C4Framework** [comment]
Animations are working as per: https://github.com/C4Framework/C4iOS/pull/233
