### ISSUE TITLE
Perspective Transform not Applying correctly to shapeLayer

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#195]
Visual perspective is not applied to a shapeLayer.

I have implemented a basic test for applying transforms to C4Rectangle (plan is to get this working with CATransform3D objects, and then implement the same actions by using C4Transform).

Main view controller:
```
e.addTapGestureRecognizer({ location, status in
    var t = CATransform3DIdentity
    t.m34 = 1.0 / 500
    t = CATransform3DRotate(t, CGFloat(M_PI / 6.0), 0.0, 1.0, 0.0)
    e.transform = t
})
```

C4Rectangle: 
```
public var transform: CATransform3D = CATransform3DMakeTranslation(0,0,0) {
    didSet {
        animateKeyPath("transform.rotation.y", toValue:NSValue(CATransform3D:transform))
    }
}
```

Tapping on the view should turn the layer in place, with simulated 3D perspective distortion. The layer applies the transform, but perspective is not added:

In the previous version of C4, changing the value of the `m34` property of a transform should result in perspective:

lines `292` to `303` in `C4Control.m` 
```
- (CGFloat)perspectiveDistance {
    return 1. / self.view.layer.transform.m34;
}

- (void)setPerspectiveDistance:(CGFloat)distance {
    CATransform3D t = self.view.layer.transform;
    if (distance != 0.0f)
        t.m34 = 1. / distance;
    else
        t.m34 = 0.;
    [self setLayerTransform:t];
}
```
(see: https://github.com/C4Framework/C4iOS/blob/master/C4/C4Control.m)

This doesn't happen... What results is the same "squared" perspective distortion that happens when `.m34 == 0`...

Starting with:
![0](https://cloud.githubusercontent.com/assets/1447498/5574512/d543b7d0-8f75-11e4-81df-5893e7626f6b.png)

We end up with:
![1](https://cloud.githubusercontent.com/assets/1447498/5574514/de703626-8f75-11e4-9615-8500813b9e41.png)

As you can see, there is no perspective being applied.

**Comment by aleph7** [comment]
You can now do

    var t = C4Transform()
    t[2, 3] = 1.0 / 500
    t.rotate(M_PI / 6.0, axis: C4Vector(x: 0, y: 1, z: 0))
    r.transform = t

**Comment by C4Framework** [comment]
Nice, just tried it out. I like the specification of the axis.
