### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#207]
All code should be documented prior to the milestone.

**Comment by C4Framework** [comment]
@aleph7 can you have a look at: https://github.com/C4Framework/C4iOS/commit/461f0ae55994bf100aca1e4b609d241a410a9253

I'll start hacking away at documentation in the next few days, there's a lot to get done.

**Comment by aleph7** [comment]
What do you think about line breaks? Should we leave them out or should we break at column 120, or 80? I like not having to worry about that when writing comments but it looks bad on github: https://github.com/C4Framework/C4iOS/blob/461f0ae55994bf100aca1e4b609d241a410a9253/C4Core/C4Color.swift

**Comment by aleph7** [comment]
Otherwise looks good.

**Comment by C4Framework** [comment]
small detail, but it will keep the look of the source clean.
github is 120c wide, i'll set a page guide column in Xcode and stick to that.
