### ISSUE TITLE
Create Audio Sample Object

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#212]
Should have same functionality as Obj-C object.

**Comment by C4Framework** [comment]
Created a new structure for Audio files and player:

https://github.com/C4Framework/C4iOS/tree/212-Audio-Sample

It uses the same style that we've been using elsewhere:

```
init(object)
init([obj1, obj2])
```

I can apply this structure to `C4Movie` as well, for consistency.

**Comment by aleph7** [comment]
That branch is pretty empty.

**Comment by C4Framework** [comment]
Repo is on my comp at work, didn't get in today to push it.

**Comment by C4Framework** [comment]
Should be fixed now, with: bb692a181548b8a982811376a03b62423edc4b71

**Comment by aleph7** [comment]
It was a rebase mess, I fixed it along with a couple of bugs: d4e8150f854f9f3336e47ce690bef7e131f90310

**Comment by C4Framework** [comment]
Learning curve is like cycling up Seymour. Thanks.
