### ISSUE TITLE
Review C4Font.swift

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#226]
Two reasons for wrapping UIFont:

1) preserves the "style" of objects like so:

```
C4View {
   var view : UIView
}

C4Font {
    var font: UIFont 
}
```

2) allows for working consistently with doubles, where the following would need an explicit cast to `Double`:
```
let s1 = C4TextShape("shape 1", font: aUIFont)
let s2 = C4TextShape("shape 2", font: aUIFont)

s2.origin = C4Point(s1.origin.x, Double(aUIFont.lineHeight))
```

**Comment by aleph7** [comment]
I don't think it's necessary. I'd rather have something like

    let s1 = C4TextSjape("shape 1", fontName: "Helvetica", fontSize: 24)
    s2.origin = C4Point(s1.origin.x, s1.origin.y + s1.size.height

**Comment by C4Framework** [comment]
A couple of things:

1) This way we can't reuse the same font across multiple objects.

2) `height` isn't actually line height, i.e. if someone wants to do layout based on properties of the font like: 
* pointSize
* ascender
* descender
* leading
* capHeight
* xHeight
* lineHeight

This image shows the use of lineHeight (left) v. height (right):
![screen shot 2015-01-04 at 11 56 25 am](https://cloud.githubusercontent.com/assets/1447498/5607261/d21afae0-9408-11e4-9594-e23dd9d4e755.png)

code:
```
height.origin = C4Point(100,line.origin.y+font.lineHeight)
height2.origin = C4Point(200,line2.origin.y+line2.height)
```

**Comment by aleph7** [comment]
Alright, you win.
