### ISSUE TITLE
Review C4Object.swift

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#227]
`C4View` is the base object for UI elements, and it conforms to the `EventSource` protocol. 

The `C4Object` class I created was essentially a non-view version of the same thing: i.e. all non-view objects could inherit from this one. 

An alternative is: 
```
extension NSObject <EventSource> {
   //stuff...
}
```

**Comment by C4Framework** [comment]
Also, C4Sample will be a simple audio file player. It will need to be an NSObject, alternatively a C4Object.

**Comment by aleph7** [comment]
If the only point of C4Object is to have event dispatch I'd rather turn C4EventSource into a class and have other classes inherit from it.

**Comment by C4Framework** [comment]
Agreed, that's clearer.
