### ISSUE TITLE
Archiving old branches

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#228]
There are a bunch of old branches from a long time ago. I suggest removing them from the list. 

As per: http://stackoverflow.com/questions/1307114/how-can-i-archive-git-branches 

We can tag them and then delete them which will keep a reference so they won't actually be deleted. Then, we can have branches that are specifically for experiments and additions to merge to the master.

Thoughts?

**Comment by aleph7** [comment]
Yes, let's do it. We might not even need to tag some of those.

**Comment by aleph7** [comment]
Maybe tag them in your machine and don't push the tags. So you'll have them in case you ever need them.

**Comment by C4Framework** [comment]
Tagged on my machine, deleted locally.

Also, deleted on github. GH has a nice delete function that removes the branch and then provides a restore button, so we can bring back any of the branches at any time. I left the ObjC branch.
