### ISSUE TITLE
Review Animation Methods in C4Image

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#232]
Review lines 177 to 197 in `C4Image`: https://github.com/C4Framework/C4iOS/blob/45dda573770239e4ff044176eb94e825f93f8e00/C4UI/C4Image.swift

I copied these methods from `C4Shape`, however, I am wondering if they should be consolidated into `C4View` rather than being slightly different versions in each of `C4View`'s subclasses.

**Comment by C4Framework** [comment]
I will create a pull request after review.

**Comment by aleph7** [comment]
This is all going away with the new animation

**Comment by C4Framework** [comment]
great
