### ISSUE TITLE
Use of snippets

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#248]
Is it possible to use snippets to change Xcode's completion from:

```
C4ViewAnimation(duration: <#NSTimeInterval#>, animations: <#() -> Void##() -> Void#>)
```

to

```
C4ViewAnimation(duration: <#NSTimeInterval#>) {}
```

If so, it would be great to add subtle things like this to other methods as well, like:

```
delay(duration:<#NSTimerInterval#>) {}
```

**Comment by C4Framework** [comment]
@aleph7, is this possible?

**Comment by aleph7** [comment]
You can add your own snippets by dragging them into the snippets list, but not sure if it can be done from the installer.

**Comment by C4Framework** [comment]
I had a look, snippets won't solve the problem of overriding Xcode's autocompletion system. As far as I can tell, there's also no way to figure out "how" Xcode is determining how to autocomplete, nor is there a way to override what it's doing (even via documentation tricks).
