### ISSUE TITLE
New project creation different than Xcode default and can delete user data

### ISSUE THREAD

**Issue by ybakos** [C4Framework/C4iOS#255]
When creating a new project with Xcode, once a folder is selected, Xcode will create a _new_ folder based on the project name, and place the project assets inside of it.

The C4 new project option in Xcode does not follow this convention. When creating a new C4 project, the selected folder gets entirely overwritten, with project assets placed inside of it. This is different from creating a new folder _inside_ the selected one.

The problem with this, other than being inconsistent, is that if an experienced Xcode user, or even a novice user, chooses to create a new project on the Desktop, one's entire desktop gets deleted.

OSX 10.9, Xcode 6.1.1, C4iOS installer iOS7.pkg.

**Comment by C4Framework** [comment]
Had a look into this and found that there are 3 issues with the current installer:

1. The location of the installer files changed from Xcode 5 to Xcode 6 (fixed, see 2.)
2. The C4iOSInstaller repo contains the build scripts for updating the installer, some details needed changing (fixed, see 1.)
3. The actual structure of template files has changed in Xcode 6+, these changes are undocumented so I'll have to go through each file, rebuilding from scratch

**Comment by C4Framework** [comment]
Fixed

New installer is up at: http://www.c4ios.com/code/

That was a major update to the installer that I'd been putting off since Sept., it sucks rebuilding that thing. 

But, now any new installers will be a piece of cake (I had to learn all the new Xcode 6 template structure / behaviour by inferring it from xml files).

**Comment by ybakos** [comment]
Wow that was fast; I knew it would be a bit painful. Thanks for the update, I'll try it asap.

**Comment by C4Framework** [comment]
yeah, someone else emailed me with a deleted desktop yesterday, so i put my head down and got it done.

**Comment by ybakos** [comment]
Just writing to confirm that the new project template does work. Once issue, however is that running the new C4 installer does not seem to overwrite the old project template. Opening a separate issue for this in case this is not by design.
