### ISSUE TITLE
Recent installer does not remove older C4 project templates

### ISSUE THREAD

**Issue by ybakos** [C4Framework/C4iOS#256]
Running the latest C4 installer (Feb. 9, 2015) creates a duplicate Xcode project template in the Xcode UI for creating new projects, causing ambiguity for a user who has already installed earlier versions of C4. A screenshot is attached.

The resolution is to manually delete all C4 xctemplate directories within the Xcode.app package, and then re-run the installer.

![screen shot 2015-02-10 at 8 15 12 am](https://cloud.githubusercontent.com/assets/5502/6128802/c4685aba-b0fe-11e4-975e-6041bd799dd5.png)

**Comment by C4Framework** [comment]
right, they have different identifiers... i'll think about it, i could possibly write a script that gets run pre-install

**Comment by ybakos** [comment]
Maybe a short solution would be to update the description, so the new one mentions something about Xcode 6. I could send a pull request for this approach if you want. (Sorry, I should have posted this issue in https://github.com/C4Framework/C4iOSInstaller/issues)

**Comment by C4Framework** [comment]
yeah, just a statement could work for now, letting people know that on Xcode 6 this will happen... when a new Xcode beta is released this won't be a prob because people will have to reinstall the templates anyways.
