### ISSUE TITLE
Installer creates "/Users/travis" folder

### ISSUE THREAD

**Issue by aylwinlo** [C4Framework/C4iOS#258]
I just noticed that the C4 doc is installed at this location on my machine:
/Users/travis/Library/Developer/Shared/Documentation/DocSets/com.C4iOS.C4.docset

I don't have any users named travis on my system! I'm assuming it should be installed here instead:
~/Library/Developer/Shared/Documentation/DocSets/com.C4iOS.C4.docset

**Comment by C4Framework** [comment]
Brilliant. Will have a look at the installer, thanks.

**Comment by C4Framework** [comment]
Should be closed with the new installer we are working on.

**Comment by C4Framework** [comment]
should be closed with #571

I checked the installer scripts and there is no reference to user or travis.
