### ISSUE TITLE
Importing compiled framework results in errors.

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#322]
I took the compiled frameworks from the `C4iOS` project, added them the `Library > Frameworks` and then linked them into a new project. (NOTE: I'm setting up a project that links libs so that I can recreate it as a template that we can load from an installer).

My main `ViewController` looks like: 

```
import UIKit
import C4Core
import C4UI
import C4Animation

class ViewController: C4CanvasController {
    override func setup() {

    }
}
```

I get the following two errors: 

`'C4CanvasController' is unavailable: cannot find Swift declaration for this class`

`Method does not override any method from its superclass`

![screen shot 2015-06-29 at 12 12 49 pm](https://cloud.githubusercontent.com/assets/1447498/8412589/be74f402-1e58-11e5-945d-2a50c3d306f7.png)

Also, I receive the following warning when only linking the projects (i.e. not calling any classes or methods from them):

```(null): Ld: warning: ld: warning: ignoring file /Library/Frameworks/C4Core.framework/C4Core, missing required architecture x86_64 in file /Library/Frameworks/C4Core.framework/C4Core (2 slices)ignoring file /Library/Frameworks/C4UI.framework/C4UI, missing required architecture x86_64 in file /Library/Frameworks/C4UI.framework/C4UI (2 slices)ignoring file /Library/Frameworks/C4Animation.framework/C4Animation, missing required architecture x86_64 in file /Library/Frameworks/C4Animation.framework/C4Animation (2 slices)```

**Comment by C4Framework** [comment]
@aleph7 any thoughts?

**Comment by aleph7** [comment]
How did you compile them? You need to go Product -> Archive

**Comment by C4Framework** [comment]
Yeah, archived then dragged them into Library > Frameworks, still no go.
Might be my project settings... Can you archive them and push your project settings?

**Comment by aleph7** [comment]
Looks like copying to `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/` and `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/` is the way to go but I still get some error.

**Comment by aleph7** [comment]
That actually works, just remember to include CoreAudio as well.

**Comment by C4Framework** [comment]
1. delete xcode 6.4, xcode 7.3-beta
2. delete library/developer (entire folder was something like 17GB, fyi)
3. install 6.4 from app store
4. create new iOS swift project
5. run in sim
6. quit xcode, sim
7. drop two sets of frames into Xcode
8. open project
9. import C4Core / C4UI (works)
10. C4CanvasController (doesn’t work)
<img width="548" alt="screen shot 2015-07-12 at 10 09 24 pm" src="https://cloud.githubusercontent.com/assets/1447498/8643145/6e1c2fa2-28e4-11e5-926d-84ce8eed47fb.png">

11. add: 
<img width="1413" alt="screen shot 2015-07-12 at 10 16 39 pm" src="https://cloud.githubusercontent.com/assets/1447498/8643147/75626592-28e4-11e5-8b66-97d2800fb9f8.png">

**compiles!**

12. run, crashes: 
```
dyld: Library not loaded: @rpath/libswiftCoreAudio.dylib

  Referenced from: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/C4UI.framework/C4UI

  Reason: image not found
```

- Tried deleting derived data and cleaning, still doesn’t work

- Tried importing frameworks directly to project (via, v Linked Frameworks and Libraries) option, still doesn’t work

**NOTE: still requires import call even w/ pointer to the right directory**

**Comment by aleph7** [comment]
Did you try adding it as an embedded framework?

**Comment by C4Framework** [comment]
i'd have to add both sim and os versions... will try

**Comment by C4Framework** [comment]
embedding works in the simulator

**Comment by C4Framework** [comment]
but, not on the device...

1. i tried embedding both sets of frameworks
2. i tried removing the set of simulator frameworks

**Comment by C4Framework** [comment]
fixed with: https://github.com/C4Framework/C4iOS/releases/download/1.0.0/C4-1.0.0.zip
