### ISSUE TITLE
Add C4iOS to Xcode project

### ISSUE THREAD

**Issue by christophz** [C4Framework/C4iOS#323]
I cannot get C4 running in my new Xcode project. Since the installer isn't working for (the current version of) Xcode anymore, how can I set up a project? I don't find any instructions for that. Can you give me some instructions how I accomplish adding the dependencies?

Thanks!

**Comment by C4Framework** [comment]
Hey Christoph,

Which version are you interested in? The ObjC branch or Swift?

**Comment by C4Framework** [comment]
Simplest way to get a new project now, for ObjC:

1. Download the ObjC branch

2. Copy the folder (once it has been unzipped)
<img width="431" alt="screen shot 2015-07-12 at 4 28 42 pm" src="https://cloud.githubusercontent.com/assets/1447498/8640610/2c1c86a0-28b3-11e5-81dd-74320add8fd5.png">

3. Rename the copied folder (e.g. MyProject)
<img width="384" alt="screen shot 2015-07-12 at 4 30 43 pm" src="https://cloud.githubusercontent.com/assets/1447498/8640618/5e7d7186-28b3-11e5-8698-9b5ff89bf48f.png">

4. Double-click on MyProject > C4iOS.xcodeproj

5. Select the C4iOS Xcode Project (top element) in the Project Navigator

6. Double-click the title of the C4iOS target (under the General tab) and change it to "MyProject"
<img width="430" alt="screen shot 2015-07-12 at 4 29 07 pm" src="https://cloud.githubusercontent.com/assets/1447498/8640614/4159fe1c-28b3-11e5-9972-0ea477729247.png">

7. Build and Run

**Comment by C4Framework** [comment]
For the new C4Swift branch:

1. Copy or Clone the current C4iOS master branch

2. Create a new Xcode project, iOS, Swift only

3. Right-Click on ViewController.swift and choose "Add Files To..." option
<img width="1440" alt="screen shot 2015-07-12 at 4 42 27 pm" src="https://cloud.githubusercontent.com/assets/1447498/8640690/b737d6ac-28b5-11e5-96a4-699b006fd3f1.png">

4. Choose the C4iOS.xcodeproj you just cloned  

5. In Project Navigator, choose MyProjectSwift 

6. Under General, click the + under the "Embedded Binaries" section

7. Choose C4Core and C4UI frameworks
<img width="1440" alt="screen shot 2015-07-12 at 4 49 14 pm" src="https://cloud.githubusercontent.com/assets/1447498/8640699/fe235546-28b5-11e5-8507-ade53b2b565b.png">

8. Update your ViewController to look like: 

```
import UIKit
import C4Core
import C4UI

class ViewController: C4CanvasController {
    override func setup() {
        C4Log("MyProjectSwift")
    }
}
```

9. Build + Run

**Comment by C4Framework** [comment]
p.s. we're working on a new installer for the Swift version

**Comment by christophz** [comment]
Thanks for your reply! I want to use the *Swift* version.

I followed your instructions. However, I can't choose **C4UI.framework** and **C4UI.framework**, they're not available after I added the master files, only **C4.framework**. Is there something I miss?

<img width="1405" alt="bildschirmfoto 2015-07-13 um 12 08 40" src="https://cloud.githubusercontent.com/assets/2182082/8647447/5324afe8-2958-11e5-89de-e4c7ec129de0.png">
<img width="711" alt="bildschirmfoto 2015-07-13 um 12 08 52" src="https://cloud.githubusercontent.com/assets/2182082/8647450/5891a5b2-2958-11e5-9e7c-343c2510ce8d.png">

**Comment by C4Framework** [comment]
Yea! Actually, right after I posted these @aleph7 pushed a big change that reduced the project from 2 frameworks to 1. Literally, just an hour or two after I posted the project structure changed.

So, yes, it should be the same process but only with C4.framework

**Comment by C4Framework** [comment]
@christophz did this work for you?

**Comment by christophz** [comment]
Yeah, it finally worked. First I was confused about the red flag on the import statement line, but it disappeared after compiling.

Thanks a lot for your help! I am eager to try the Swift version of C4! Dope new logo, by the way! :)
