### ISSUE TITLE
After repeatCount > 0, animation snaps to new position when complete

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#338]
I am trying to add a repeatCount option to C4Animation, but I'm running into an issue where upon completion the animation snaps to its new setting rather than preserving its visual state. For example, this animation shows 1 repeat:

![autoreverse](https://cloud.githubusercontent.com/assets/1447498/8816242/16d34bd0-2fd9-11e5-87a1-15b183461cf9.gif)

The ObjC version solved the issue like this: http://stackoverflow.com/a/11526776/1218605

But, the way `C4ViewAnimation` processes a block of animations and then calls `self.animations()` basically prevents the previous solution from being possible because we don't know what's happening inside the `animations` block.

This also applies to conditions where we might set `autoReverse = true` and `repeat = false`.

**Comment by C4Framework** [comment]
Also, in this example, I've done the following: 

In `C4Animation`, I added: 

```    public var repeatCount = 0.0
```

In `C4ViewAnimation`, I added: 

```
if repeatCount > 0.0 {
    options |= ~UIViewAnimationOptions.Repeat
}

UIView.animateWithDuration(duration, delay: delay, options: options, animations: {
    if self.repeatCount > 0.0 {
        UIView.setAnimationRepeatCount(Float(self.repeatCount))
    }
    ...
}
```

**Comment by aleph7** [comment]
This works:
```
class ViewController: C4CanvasController {
    override func setup() {
        let c = C4Circle(center: C4Point(), radius: 100)
        canvas.add(c)

        let anim = C4ViewAnimation(duration: 0.5) {
            c.center = self.canvas.center
        }
        anim.repeatCount = 2
        anim.autoreverses = true
        anim.addCompletionObserver({
            c.center = C4Point()
        })
        delay(1.0) {
            anim.animate()
        }
    }
}
```

**Comment by C4Framework** [comment]
Snap.
I need to learn how to read.
