### ISSUE TITLE
Layer animations not adopting UIView animationOptions

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#352]
In this example, the view autoreverses its position, but the layer's `lineWidth` does not:

```
override func setup() {
    let s = C4Ellipse(frame: C4Rect(0,0,100,100))
    let originalCenter = s.center
    canvas.add(s)
    
    let anim = C4ViewAnimation(duration: 1.0) {
        s.center = self.canvas.center
        s.lineWidth = 10.0
    }
    
    anim.autoreverses = true
    anim.addCompletionObserver { () -> Void in
        s.center = originalCenter
    }
    
    delay(1.0) {
        anim.animate()
    }
}
```

I've been trying to find ways to fix this but haven't, yet. I think it's an important element that definitely needs to be solved.

Here's an article on mixing calayer and uiview animations (not sure if it's relevant though):
http://www.objc.io/issues/12-animations/view-layer-synergy/#learning-from-uikit

**Comment by C4Framework** [comment]
Here's another option:
https://github.com/iMartinKiss/UIView-AnimatedProperty/blob/master/Sources/UIView%2BAnimatedProperty.m

**Comment by C4Framework** [comment]
@aleph7 no rush, just assigning so I don't forget to talk to you about it.

**Comment by aleph7** [comment]
Fixed
