### ISSUE TITLE
Possible unexpected Behaviour for Group Animation Properties

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#370]
I tried to apply properties to the objects in a `C4ViewAnimationGroup`:

```
let animA = C4ViewAnimation(duration: 1.0) {
    lineA.a = C4Point(lineA.a.x,lineA.a.y-100)
}

let animB = C4ViewAnimation(duration: 0.5) {
    lineB.b = C4Point(lineB.b.x,lineB.b.y+100)
}

let grp = C4ViewAnimationGroup(animations: [animA,animB])
grp.autoreverses = true
grp.repeats = true

delay(1.0) {
    grp.animate()
}
```

However, the `autoreverses` and `repeat` animations are not applied to the objects.

Should this be the case? Or, should we have the group temporarily override the behaviours of the animations in its array?

**Comment by aleph7** [comment]
It doesn't really make sense to have these properties on an animation group. Every animation in the group can have a different duration, so should all animation repeat out of sync or should they all wait for the last animation to complete before they repeat? I think a better solution would be to print a warning that these properties are ignored for an animation group, and also say it in the documentation. What do you think?

**Comment by C4Framework** [comment]
Yeah, this seems reasonable for groups. But what about for sequences?

I could see building a sequence [A, B, C] then at some point wanting that animation sequence to execute in reverse [C, B, A]... currently, I have to construct the opposite animation (i.e. latter) instead of saying `AnimationSeq.reverses = true`.

**Comment by aleph7** [comment]
Yeah, that would make sense. But it would be hard to implement, how do you run an animation once in reverse?

**Comment by C4Framework** [comment]
yeah, removing the bug label.
let's keep a thread on this... it might not be that big a deal to not have it, i remember i ran into wanting it when doing the in/out animations for the Cosmos app menu.
