### ISSUE TITLE
Using C4Shape(frame:) initializer

### ISSUE THREAD

**Issue by Ollstar** [C4Framework/C4iOS#374]
Using this code:
```
let frame = C4Rect(0, 0, self.canvas.width*0.9, self.canvas.height/5.0)
red =  C4Shape(frame: frame)
```
Expected:
A generic or basic shape with the specified frame
Result:
No errors, but no drawn shape. Maybe this method can warn when there is no path for the shape.

**Comment by C4Framework** [comment]
Similar to #372, in that this issue is about making it easier for a developer to understand why the initializer isn't working as expected
