### ISSUE TITLE
C4Transform doesn't change C4Shape

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#564]
The following should create 10 objects and rotate each one, but none of the shapes rotate:

```
for i in 0..<10 {
    let angle = Double(i) * M_PI / 5.0
    let rot = C4Transform.makeRotation(angle)
    let c = C4Rectangle(frame: C4Rect(0,0,50,50))
    c.center = C4Point(view.center)
    c.transform = rot
    view.add(c)
}
```

<img width="592" alt="screen shot 2015-10-12 at 9 43 19 pm" src="https://cloud.githubusercontent.com/assets/1447498/10445662/4aefb18c-712a-11e5-9a60-9b5b6f642dc8.png">

**Comment by aleph7** [comment]
This seems to be a serious problem on OS X: http://jwilling.com/blog/osx-animations/

**Comment by C4Framework** [comment]
Yeah, that looks like a "clean" and "nasty" approach.
