### ISSUE TITLE
AnchorPoint doesn't affect C4View

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#565]
The following should cause the specified rectangle to sit right of center, with the pink dot at the center. 

```
let c = C4Circle(center: C4Point(view.center), radius: 5)
c.fillColor = C4Pink
let r = C4Rectangle(frame: C4Rect(0,0,50,50))
r.anchorPoint = C4Point(-2.0,0.5)
r.center = C4Point(view.center)
view.add(r)
view.add(c)
```

<img width="592" alt="screen shot 2015-10-12 at 9 46 46 pm" src="https://cloud.githubusercontent.com/assets/1447498/10445694/c2d4392a-712a-11e5-8439-4c01cc80c96e.png">

**Comment by aleph7** [comment]
Same problem as #564
