### ISSUE TITLE
C4View clipping behaviour

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#567]
It should be possible to toggle a view's clipping behaviour. However, the `wantsDefaultClipping` option is not a variable and must be overridden. The following (or similar) should be possible:

```
r.view.wantsDefaultClipping = false
```

<img width="592" alt="screen shot 2015-10-12 at 10 08 09 pm" src="https://cloud.githubusercontent.com/assets/1447498/10445925/d5ab6c3c-712d-11e5-818a-12e50d7fe0c6.png">

**Comment by aleph7** [comment]
Fixed by properly computing shape bounds
