### ISSUE TITLE
Install via Carthage

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#570]
We should be able to install the framework via carthage. When done, I can create an intro tutorial on how to do this.

**Comment by aleph7** [comment]
1. Install [Carthage](https://github.com/Carthage/Carthage)
2. Create `Cartfile` and in it paste `github "C4Framework/C4iOS" ~> 1.0.1`
3. Run `carthage update`
4. In your project reference the framework in `Carthage/Build/iOS/C4.framework`

**Comment by C4Framework** [comment]
Carthage doesn't install on the latest OSX (at least not on mine, 10.11), this could be a problem.

**Comment by aleph7** [comment]
Works for me, did you download `Carthage.pkg`? Their brew version is currently broken.

**Comment by C4Framework** [comment]
Just found a direct download of carthage. Yeah.

**Comment by C4Framework** [comment]
It's a bit of a raw approach, though very lean.

I would consider having the carthage file part of the Xcode installer, with an option: 
1) install hard coded files
2) install carthage file, already created as an executable

**Comment by C4Framework** [comment]
I get the following warnings from updating C4iOS via carthage:

```
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/Developer/Library/Frameworks'
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/Developer/Library/Frameworks'
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks'
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks'
```

**Comment by aleph7** [comment]
I say let's have options and let them choose. We should support coocapods too. If they choose to use carthage they can figure it out.

**Comment by C4Framework** [comment]
ok, that makes the installer easy and we can leave it as-is, basically.

>> carthage, cocoa pods, installer, clone + embed

I can make short walkthroughs for each of these options and then leave it to them to choose.

**Comment by aleph7** [comment]
:+1:
