### ISSUE TITLE
backgroundColor not setting for C4View

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#574]
This does NOT work:

```
class ViewController: C4CanvasController {
    override func setup() {
        canvas.backgroundColor = C4Blue
    }
}
```

This DOES work:

```
class ViewController: C4CanvasController {
    override func setup() {
        canvas.view.layer?.backgroundColor = C4Blue.CGColor
    }
}
```

I've traced the error to C4View's `backgroundColor` property:

<img width="798" alt="screen shot 2015-10-27 at 2 40 51 am" src="https://cloud.githubusercontent.com/assets/1447498/10754406/9af6e3a0-7c54-11e5-9978-e48391ab098a.png">

Specifically, I think the error is in ` if let layerView = view as? LayerView`. 

In the following code `lv` returns as a `NativeView` not a `LayerView`, so the statement returns false and the setting of the backgroundColor never executes:

```
set {
    let lv = view
    if let layerView = view as? LayerView {
        if let color = newValue {
            layerView.backgroundColor = NativeColor(color)
        } else {
            layerView.backgroundColor = nil
        }
    }
}
```

**Comment by aleph7** [comment]
Yeah, `NSView` doesn't have a background color property. That's why I added `LayerView`. But by default view controllers create `NSView`s, you have to explicitly say you need a `LayerView` either in the xib, storyboard or in `loadView()`

**Comment by aleph7** [comment]
I guess a fix for this would be to implement `loadView()` in `C4CanvasController` but this may break loading it from an xib file. Will look into it.

**Comment by C4Framework** [comment]
ok, what's the diff between LayerView and NativeView?

**Comment by aleph7** [comment]
NativeView is NSView, LayerView is a subclass of NSView that adds a background color property and a few other requirements that need to be there for it to work. (Setting the layer's backgroundColor is not enough)

**Comment by C4Framework** [comment]
This is an Interface Builder issue. When you create a new OSX project and embed C4, you need to also change the Main.Storyboard's view from NSView to LayerView.

![screen shot 2015-10-27 at 2 54 58 pm](https://cloud.githubusercontent.com/assets/1447498/10773816/df4b0886-7cba-11e5-8947-07c148fbdb32.png)
