### ISSUE TITLE
loadView override resizes main application window at launch

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#580]
This commit:
https://github.com/C4Framework/C4iOS/commit/e41c71f560898b9a9454c9c802ec3a55ddba0857

Fixed #573, however it also added a new bug.

This is a 2-part problem.

First, I'm working with this in my main application setup():

```
override func setup() {
    let c = C4Circle(center: canvas.center, radius: 20)
    canvas.add(c)
}
```

I expect this to be placed in the center of my canvas.

However, I was getting this window:

![screen shot 2015-10-29 at 8 36 27 pm](https://cloud.githubusercontent.com/assets/1447498/10837936/c1a408a0-7e7c-11e5-8525-d9527a42347b.png)

In setup, I ran:

```
print(NSApplication.sharedApplication().windows[0].frame)
```

Which produced:

```
(235.0, 289.0, 480.0, 292.0)
```

Which is NOT where the window appears:

<img width="1920" alt="screen shot 2015-10-29 at 8 38 15 pm" src="https://cloud.githubusercontent.com/assets/1447498/10837954/07c27e02-7e7d-11e5-889c-1a4248ab6ad2.png">

Turns out that my application's main window has a Restorable option in Interface Builder:

<img width="889" alt="screen shot 2015-10-29 at 8 39 33 pm" src="https://cloud.githubusercontent.com/assets/1447498/10837968/3895a1a8-7e7d-11e5-907b-42dc27b7b088.png">

So I unchecked that and I get:

![screen shot 2015-10-29 at 8 30 31 pm](https://cloud.githubusercontent.com/assets/1447498/10837971/3d7d6c28-7e7d-11e5-9a23-d8fecb09aeb2.png)

Which is ALSO not what the window should look like...

So, to HACK this I had to do the following:

In C4CanvasController, modify the import to include a variable for AppKit

```
#if os(iOS)
import UIKit
#elseif os(OSX)
import AppKit
var applicationDidLoad = false
#endif
```

Then, modify `loadView()` to the following:

```
public override func loadView() {
    #if os(OSX)
        if applicationDidLoad == false {
            let window = NSApplication.sharedApplication().windows[0]
            var bounds = window.frame
            bounds.origin = CGPointZero
            view = LayerView(frame: bounds)
            applicationDidLoad = true
        } else {
            view = LayerView(frame: CGRect(x: 0,y: 0,width: 50,height: 50))
        }
    #endif
}
```

Now I get:

![screen shot 2015-10-29 at 8 42 07 pm](https://cloud.githubusercontent.com/assets/1447498/10838000/8d519850-7e7d-11e5-8fc2-4dc8077daa4e.png)

Which is expected.

HOWEVER, the window alway reappears in the original spot determined by IB. Not, quite, what, I expect.

**POSSIBLE SOLUTION**

Implement a `restorationClass` per the [NSWindow Reference](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWindow_Class/#//apple_ref/occ/instp/NSWindow/restorationClass)

**Comment by C4Framework** [comment]
@aleph7 can you review this post for me? I can work on the proposed solution.

**Comment by C4Framework** [comment]
probably sufficient to remove Restorable and set the application's window to:

<img width="740" alt="screen shot 2015-10-29 at 9 10 34 pm" src="https://cloud.githubusercontent.com/assets/1447498/10838300/84b9c4d4-7e81-11e5-958f-b6add5f6a113.png">

... until someone specifically asks for this to be fixed.

**Comment by Ollstar** [comment]
When I started with the OSX examples everything was starting in the bottom left corner like that. Eventually, without me changing anything they started to become centred and with the correct frame. This probably doesn't help but I'm not sure if the simulator reflects the correct window.

**Comment by aleph7** [comment]
The real solution to this is to use auto layout. Instead of setting the center do 

```
let c = C4Circle(center: canvas.center, radius: 20)
canvas.add(c)
c.centerXAnchor.constraintEqualToAnchor(canvas.centerXAnchor).active = true
c.centerYAnchor.constraintEqualToAnchor(canvas.centerYAnchor).active = true
```

**Comment by aleph7** [comment]
The other solution is to override `viewDidLayoutSubviews` and set the center there.
