### ISSUE TITLE
Add image property for visible objects

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#593]
`let C4Image = shape.image`

This should take into consideration the bounds of shape line widths.

`let C4Image = view.image`

This should render all sublayers, taking into the view's masksToBounds property.

**Comment by aleph7** [comment]
May be better to do `shape.render()`

**Comment by C4Framework** [comment]
yup, the above were just placeholders...

there are options I was planning to consider like:

`obj.bitmap()`
`obj.bitmap(dpi,scale)`

also

`obj.drawIn(pdfContext)`

will have a think on all these and post something I hope is reasonably intelligent..
