### ISSUE TITLE
Gradient Fill could work with pattern images

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#602]
Instead of setting the background of a specific shape, it might be better to use pattern images to fill the shape, instead of the current approach.

However, I see a problem with using pattern images: They default to rendering from `{0,0}`, and depending on the shape's current location (ie. in cases like `C4Star`, the layer origin of the shape often isn't at `{0,0}`. This results in the following:

```
override func setup() {
    let star = C4Star(center: canvas.center, pointCount: 10, innerRadius: 50, outerRadius: 80)
    let g = C4Gradient(frame: star.frame, colors: [C4Blue, C4Pink])
    let i = g.render()!
    star.fillColor = C4Color(UIColor(patternImage: i.uiimage))
    canvas.add(star)
}
```

4s
![simulator screen shot jan 20 2016 10 37 58 pm](https://cloud.githubusercontent.com/assets/1447498/12473396/b04d4b94-bfc6-11e5-9c3d-b42eaa4235a8.png)

5
![simulator screen shot jan 20 2016 10 38 44 pm](https://cloud.githubusercontent.com/assets/1447498/12473399/b8959d42-bfc6-11e5-8e44-f35af41703e0.png)

6
![simulator screen shot jan 20 2016 10 39 19 pm](https://cloud.githubusercontent.com/assets/1447498/12473444/ea9eefaa-bfc6-11e5-93fb-3fb51d2da1ca.png)

The same code produces varying effects on different screen sizes.

**Comment by C4Framework** [comment]
@aleph7 can you help with the flicker happening when animating from a solid color to pattern image color?

See this branch:
https://github.com/C4Framework/C4iOS/commit/e8727bd89db588ad251b1285ebaf31eb97a4b204

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/1447498/12491403/bccc28ea-c02f-11e5-88b7-9d7199331982.gif)

Try this example:
```
override func setup() {
    let star = C4Star(center: canvas.center, pointCount: 10, innerRadius: 50, outerRadius: 80)
    let g = C4Gradient(frame:star.frame, colors: [C4Blue, C4Pink])
    star.gradientFill = g
    let c = C4Circle(center: canvas.center, radius: 25)

    c.gradientFill = g
    canvas.add(star)
    canvas.add(c)

    var b = false
    let a = C4ViewAnimation(duration:1.0) {
        if b {
            g.frame = star.frame
            star.gradientFill = g
        } else {
            star.fillColor = C4Pink
        }
        b = !b
    }

    canvas.addTapGestureRecognizer { (location, state) -> () in
        a.animate()
    }
}
```

**Comment by aleph7** [comment]
I tried `star.fillColor = C4Color(UIColor(patternImage: UIImage.createWithColor(UIColor(C4Pink)!, size: CGSize(width: 1, height: 1))))` for the solid color and it works but it doesn't animate. Maybe let's stick with the current approach.

**Comment by aleph7** [comment]
The other options is doing it more like CA does it: by having a gradient layer. It's up to the user to mask that layer or change its color.

**Comment by C4Framework** [comment]
probably possible if we use CGPatternRef, but i blew my brains out trying to make that work...

**Comment by aleph7** [comment]
that looks interesting

**Comment by C4Framework** [comment]
Fixed with https://github.com/C4Framework/C4iOS/commit/a1d8515fa503d0664d8688a6b61479d53ad9248a

**Comment by C4Framework** [comment]
Note: the flickering is expected behaviour (i.e. it happens in UIKit)
