### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#603]
Over the last couple weeks we've started copying objects. A concrete example is:

```
public convenience init(_ shape: C4Shape) {
     self.init()
     let disable = C4ShapeLayer.disableActions
     C4ShapeLayer.disableActions = true
     self.path = shape.path
     shapeLayer.path = path?.CGPath
     self.frame = shape.frame
     self.lineWidth = shape.lineWidth
     self.lineDashPhase = shape.lineDashPhase
     self.lineCap = shape.lineCap
     self.lineJoin = shape.lineJoin
     self.lineDashPattern = shape.lineDashPattern
     self.fillColor = shape.fillColor
     self.strokeColor = shape.strokeColor
     self.strokeStart = shape.strokeStart
     self.strokeEnd = shape.strokeEnd
     self.miterLimit = shape.miterLimit
     updatePath()
     adjustToFitPath()
     C4ShapeLayer.disableActions = disable
 }
```

There should be a consistent approach for creating copies of objects.

The previous initialization should also copy basic view properties.

**Comment by aleph7** [comment]
I think the `convenience init(_ original: Object)` is good.

**Comment by C4Framework** [comment]
- [ ] C4View
- [ ] C4Shape
- [ ] C4Image
- [ ] C4Movie
- [ ] C4AudioPlayer
- [ ] C4Gradient
- [ ] C4Vector

**Comment by C4Framework** [comment]
@aleph7 just starting with this...

adding `init(_ original: View)` to `View` and `init(_ original: Shape)` to `Shape` causes an error: 

```
Initializer 'init' with Objective-C selector 'init:' conflicts with initializer 'init' from superclass 'View' with the same Objective-C selector
```

Without an `init(original)` on `View` we will have to initialize all the `View` properties from every subclass. This will be a bit sloppy, imo.

Can you think of a possible solution?
