### ISSUE TITLE
lerp function signature

### ISSUE THREAD

**Issue by aleph7** [C4Framework/C4iOS#607]
It should be `lerp(0, 1, at: 0.5)` instead of the current `lerp(a: 0, b: 1, param: 0.5)`

**Comment by aleph7** [comment]
Same for `C4Point`

**Comment by C4Framework** [comment]
actually, there's a lot of things like this I think could make it into this ticket

```
C4Animation(0.25) {
   ...
}
```

I can't think of them off the top of my head, but I feel like I've noticed a lot.
