### ISSUE TITLE
Float Literal Type

### ISSUE THREAD

**Issue by C4Framework** [C4Framework/C4iOS#619]
![caypi_awcaa__2m](https://cloud.githubusercontent.com/assets/1447498/13199232/81d2af9a-d7d4-11e5-8086-0ba13a843bd8.png)

**Comment by C4Framework** [comment]
@aleph7: Toyed around with this for a while, but I'm deciding to leave this one to you.

Can you provide an example of the benefit?

**Comment by aleph7** [comment]
This doesn't actually work, and I still think Double is better
