### ISSUE TITLE
Typo in Cosmos tutorial?

### ISSUE THREAD

**Issue by jeffThompson** [C4Framework/C4iOS#636]
(First of all – this is all really amazing. Thank you!)

I'm working through the Cosmos tutorial and I think there's an error that is preventing me from compiling. I'm in [chapter 5, section 1.2](http://www.c4ios.com/cosmos/5-infinite-scrollview-build/) and the line `ts.center = point` needs to be `ts!.center = point` for it to work for me.

**Comment by C4Framework** [comment]
Fixed! Thanks for the heads up.

I actually changed:

```
let ts = C4TextShape(text: "\(x)")!
```

**Comment by jeffThompson** [comment]
Cool!

I believe that causes the same error in section 2 of the same page ("Proper Setup"):
    func createIndicator(text: String, at point: C4Point) {
        let ts = C4TextShape(text: text)!
        ts.center = point
        infiniteScrollView.add(ts)
    }

**Comment by C4Framework** [comment]
Great, thanks. Got that one fixed as well.

**Comment by C4Framework** [comment]
@jeffThompson if you're still working through the cosmos tutorial, i have some news. we just updated the api and there's been some big changes! no more C4 prefix! 

But, we also updated the cosmos tutorial with new syntax. So, you might have to switch to the new style. You can work from the new [empty project](http://www.c4ios.com/cosmos/CosmosEmpty.zip) and use the [complete project](http://www.c4ios.com/cosmos/CosmosComplete.zip) as a base to catch up to where you left off.
