### ISSUE TITLE
Updating TextShape.text repositions TextShape origin to (0,0)

### ISSUE THREAD

**Issue by Ollstar** [C4Framework/C4iOS#638]
Create textshape with:
```
var pl = TextShape(text:"Red has been chosen 0 times", font: Font(name: "Helvetica", size: 14.0)!)!
```
Updating text with:
```
let ps = "Red has been chosen \(pc) times"
pl.text = ps
```
The textShape is being put in the the top left corner
![Uploading Screen Shot 2016-03-04 at 11.49.00 AM.png…]()
You can barely see but the pink textshape is in the top left.

**Comment by C4Framework** [comment]
This is expected. The reasoning: when someone is updating text, we don't know how they want it oriented to the screen, left, center, etc... so implicitly trying to determine that for them is not possible. You will have to position the shape yourself.

Try: 

```
let c = ps.origin
let ps = "Red has been chosen \(pc) times"
pl.text = ps
ps.origin = c
```
