### ISSUE TITLE
No center property of pinch gesture.

### ISSUE THREAD

**Issue by Ollstar** [C4Framework/C4iOS#639]
I have a pinch gesture added to my canvas like so:
```
canvas.addPinchGestureRecognizer { (scale, velocity, state) -> () in
}
```
I want to change the size of a view located at the center of the gesture.

Is there something like a locations property on this gesture like some of the other C4 gestures have??
If so how can I access it?

**Comment by C4Framework** [comment]
Fixed on the 1.1.x branch.
